name: Continuous Integration

on: [push] 

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      DOCKER-BUILDKIT: "1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run lint
        uses: make lint
      - name: Run unit tests
        uses: make unit-test
      - name: Build Linux binary
        uses: make PLATFORM=linus/amd64
      - name: Build Windows binary
        uses: make PLATFORM=windows/amd64