name: Continuous Integration

on: [push] 

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      DOCKER-BUILDKIT: "1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker Hub LogIn
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run lint
        run: make lint
      - name: Run unit tests
        run: make unit-test
      - name: Build Linux binary
        run: make PLATFORM=linus/amd64
      - name: Build Windows binary
        run: make PLATFORM=windows/amd64